# Generated by Django 3.2.2 on 2024-03-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posesion',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posesion',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
