# Generated by Django 3.2.2 on 2024-03-07 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acta',
            name='colindancia',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='imagen_acta',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='titulares',
        ),
        migrations.AddField(
            model_name='colindancia',
            name='acta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='colindancias', to='pos.acta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagenacta',
            name='acta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='pos.acta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='titular',
            name='acta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titulares', to='pos.acta'),
        ),
        migrations.AlterField(
            model_name='imagenacta',
            name='comentario3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
