# Generated by Django 3.2.2 on 2024-03-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acta',
            name='posesion_informal',
        ),
    ]
