# Generated by Django 3.2.2 on 2024-03-14 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColindanciaUfin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frente_descripcion', models.CharField(max_length=100)),
                ('frente_distancia', models.DecimalField(decimal_places=5, max_digits=10)),
                ('frente_n_tramos', models.IntegerField()),
                ('frente_tramos', models.JSONField()),
                ('derecha_descripcion', models.CharField(max_length=100)),
                ('derecha_distancia', models.DecimalField(decimal_places=5, max_digits=10)),
                ('derecha_n_tramos', models.IntegerField()),
                ('derecha_tramos', models.JSONField()),
                ('izquierda_descripcion', models.CharField(max_length=100)),
                ('izquierda_distancia', models.DecimalField(decimal_places=5, max_digits=10)),
                ('izquierda_n_tramos', models.IntegerField()),
                ('izquierda_tramos', models.JSONField()),
                ('fondo_descripcion', models.CharField(max_length=100)),
                ('fondo_distancia', models.DecimalField(decimal_places=5, max_digits=10)),
                ('fondo_n_tramos', models.IntegerField()),
                ('fondo_tramos', models.JSONField()),
                ('numero_lote', models.CharField(max_length=150)),
                ('numero_manzana', models.CharField(max_length=150)),
                ('area', models.DecimalField(decimal_places=5, max_digits=10)),
                ('perimetro', models.DecimalField(decimal_places=5, max_digits=10)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colindanciasUfin', to='pos.acta')),
            ],
        ),
    ]
