# Generated by Django 3.2.2 on 2024-03-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posesion',
            name='pdf_documento',
            field=models.FileField(blank=True, null=True, upload_to='posesion/'),
        ),
    ]
