# Generated by Django 3.2.2 on 2024-03-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20240322_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='area_segun_el_titular_representante',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acta',
            name='cantidad_lotes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acta',
            name='n_punto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
