# Generated by Django 3.2.2 on 2024-03-20 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20240320_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='posesion_informal',
            field=models.ForeignKey(default='43', on_delete=django.db.models.deletion.CASCADE, related_name='actas', to='pos.posesioninformal'),
        ),
    ]
