# Generated by Django 3.2.2 on 2024-03-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_posesioninformal_is_matriz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posesioninformal',
            name='conflictos_dirigenciales_pdf',
            field=models.FileField(null=True, upload_to='posesion_informal/archivos/'),
        ),
        migrations.AlterField(
            model_name='posesioninformal',
            name='imagen_satelital_pdf',
            field=models.FileField(null=True, upload_to='posesion_informal/archivos/'),
        ),
        migrations.AlterField(
            model_name='posesioninformal',
            name='zonas_arquelogicas_o_reservas_pdf',
            field=models.FileField(null=True, upload_to='posesion_informal/archivos/'),
        ),
        migrations.AlterField(
            model_name='posesioninformal',
            name='zonas_riesgo_pdf',
            field=models.FileField(null=True, upload_to='posesion_informal/archivos/'),
        ),
    ]
