# Generated by Django 3.2.2 on 2024-03-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_remove_acta_posesion_informal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenacta',
            name='boceto_pdf',
            field=models.FileField(null=True, upload_to='acta/archivos'),
        ),
        migrations.AlterField(
            model_name='imagenacta',
            name='documento_predio_pdf',
            field=models.FileField(null=True, upload_to='acta/archivos'),
        ),
    ]
