# Generated by Django 3.2.2 on 2024-03-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20240307_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosesionInformal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('coordenada_x', models.DecimalField(decimal_places=10, max_digits=30)),
                ('coordenada_y', models.DecimalField(decimal_places=10, max_digits=30)),
                ('tipo_posecion_informal', models.CharField(max_length=100)),
                ('denominacion_segun_inei', models.CharField(max_length=200)),
                ('tipo_matriz', models.CharField(max_length=150)),
                ('contexto_legal', models.CharField(max_length=150)),
                ('aciones_de_formalizacion', models.CharField(max_length=150)),
                ('tipo_calzada', models.CharField(max_length=150)),
                ('tipo_calzada_distancia', models.CharField(max_length=100)),
                ('referencia_local', models.CharField(max_length=200)),
                ('referencia_local_tiempo', models.TimeField()),
                ('ruta', models.CharField(max_length=100)),
                ('ruta_especifica', models.CharField(max_length=200)),
                ('tipo_configuracion_urbana', models.CharField(max_length=20)),
                ('numero_lotes', models.IntegerField()),
                ('numero_manzanas', models.IntegerField()),
                ('porcentaje_vivencia', models.DecimalField(decimal_places=3, max_digits=6)),
                ('equipamientos', models.JSONField()),
                ('material_predominante', models.JSONField()),
                ('servicios_basicos', models.JSONField()),
                ('zonificacion_municipal', models.BooleanField(default=True)),
                ('zonas_reservadas', models.CharField(max_length=200)),
                ('zonas_arquelogicas_o_reservas', models.BooleanField()),
                ('zonas_a_o_r_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('zonas_a_o_r_ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('zonas_riesgo', models.BooleanField()),
                ('zonas_riesgo_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('zonas_riesgo_ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('conceciones_mineras', models.CharField(max_length=100)),
                ('canales_postes_cables', models.TextField(max_length=500)),
                ('posibles_propietarios', models.TextField(max_length=500)),
                ('otros', models.CharField(blank=True, max_length=200, null=True)),
                ('conflictos_dirigenciales', models.BooleanField()),
                ('conflictos_dirigenciales_descripcion', models.TextField(max_length=300)),
                ('conflictos_judiciales', models.BooleanField()),
                ('conflictos_judiciales_descripcion', models.TextField(max_length=300)),
                ('comentarios_observaciones', models.TextField(max_length=300)),
                ('imagen_satelital', models.ImageField(upload_to='posesion_informal/')),
                ('imagen_areas_restrinjidas', models.ImageField(upload_to='posesion_informal/')),
                ('imagen_areas_restrinjidas_comentario', models.TextField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='imagenacta',
            name='firma_representante_comision',
        ),
        migrations.RemoveField(
            model_name='imagenacta',
            name='firma_supervisor_campo',
        ),
        migrations.RemoveField(
            model_name='imagenacta',
            name='firma_topografo',
        ),
        migrations.AddField(
            model_name='imagenacta',
            name='archivo_firmas',
            field=models.FileField(default=2, upload_to='acta/archivos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagenacta',
            name='boceto',
            field=models.ImageField(upload_to='acta/imagenes'),
        ),
    ]
