# Generated by Django 3.2.2 on 2024-03-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20240318_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posesion',
            name='anios_posesion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
