# Generated by Django 3.2.2 on 2024-03-21 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20240321_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='initial',
            new_name='stock',
        ),
    ]
