# Generated by Django 3.2.2 on 2024-03-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_colindanciaufin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colindanciaufin',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='colindanciaufin',
            name='derecha_distancia',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='colindanciaufin',
            name='fondo_distancia',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='colindanciaufin',
            name='frente_distancia',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='colindanciaufin',
            name='izquierda_distancia',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='colindanciaufin',
            name='perimetro',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
