# Generated by Django 3.2.2 on 2024-04-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_colindanciaufin_acta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=models.CharField(max_length=9, unique=True, verbose_name='Teléfono'),
        ),
    ]
