# Generated by Django 3.2.2 on 2024-03-21 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_rename_initial_sale_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='stock',
            new_name='initial',
        ),
    ]
