# Generated by Django 3.2.2 on 2024-03-14 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_auto_20240313_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='colindancia',
            name='derecha_direccion',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='colindancia',
            name='fondo_direccion',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='colindancia',
            name='frente_direccion',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='colindancia',
            name='izquierda_direccion',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='colindancia',
            name='acta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='colindancia', to='pos.acta'),
        ),
    ]
