# Generated by Django 3.2.2 on 2024-04-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_client_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='codigo_dlt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
