# Generated by Django 3.2.2 on 2024-03-20 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_acta_posesion_informal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='codigo_predio',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='acta',
            name='posesion_informal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actas', to='pos.posesioninformal'),
        ),
    ]
