# Generated by Django 3.2.2 on 2024-03-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_auto_20240307_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='acceso_a_via',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='acta',
            name='adjunta_toma_topografica',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='acta',
            name='apertura_de_via',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='acta',
            name='hitos_consolidados',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='acta',
            name='libre_de_riesgo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='acta',
            name='litigio_denuncia',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='acta',
            name='req_transf_de_titular',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='acta',
            name='requiere_alineamiento',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='acta',
            name='requiere_subdivision',
            field=models.CharField(max_length=10),
        ),
    ]
