# Generated by Django 3.2.2 on 2024-03-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_auto_20240320_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='codigo_predio',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
