# Generated by Django 3.2.2 on 2024-04-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_alter_acta_codigo_dlt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posesion',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posesion',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
