# Generated by Django 3.2.2 on 2024-03-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_alter_acta_codigo_predio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posesioninformal',
            name='codigo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
