# Generated by Django 3.2.2 on 2024-07-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_auto_20240430_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsctacollect',
            name='paymentNumber',
            field=models.IntegerField(default=1, verbose_name='Número de pago'),
        ),
    ]
