# Generated by Django 3.2.2 on 2024-03-21 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
