# Generated by Django 3.2.2 on 2024-03-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_auto_20240307_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='carta_poder',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
