# Generated by Django 3.2.2 on 2024-03-11 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_alter_acta_carta_poder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titular',
            name='tipo_doc',
        ),
        migrations.CreateModel(
            name='Posesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copia_doc_identidad', models.CharField(default='no', max_length=3)),
                ('apellidos', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(max_length=20)),
                ('num_doc', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('acta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posesionarios', to='pos.acta')),
            ],
        ),
    ]
