# Generated by Django 3.2.2 on 2024-03-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='birthdate',
        ),
    ]
