# Generated by Django 3.2.2 on 2024-03-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_auto_20240311_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='codigo_predio',
            field=models.CharField(default='PHY-76567576', max_length=150),
        ),
    ]
