# Generated by Django 3.2.2 on 2024-03-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_remove_client_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
