# Generated by Django 3.2.2 on 2024-03-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_acta_codigo_predio'),
    ]

    operations = [
        migrations.AddField(
            model_name='posesion',
            name='anios_posesion',
            field=models.IntegerField(default=1),
        ),
    ]
