# Generated by Django 3.2.2 on 2024-03-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_login_dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
