# Generated by Django 3.2.2 on 2024-03-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_auth_login_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(max_length=13, unique=True, verbose_name='DNI'),
        ),
    ]
