# Generated by Django 3.2.2 on 2024-03-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduletype',
            name='icon',
            field=models.CharField(max_length=100, verbose_name='Icono'),
        ),
    ]
