# Generated by Django 3.2.2 on 2024-04-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_alter_moduletype_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='name_menu',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='moduletype',
            name='name_menu',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
