# Generated by Django 3.2.2 on 2024-05-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_auto_20240429_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='url',
            field=models.CharField(max_length=100, verbose_name='Url'),
        ),
    ]
